service: aws-node-http-api-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  # Allow permisions to access DynamoDB
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:429409050943:table/TodoTable

# Lambda
functions:
  addTodo:
    handler: src/addTodo.handler
    events:
      - http:
          path: /todos
          method: post
  fetchTodos:
    handler: src/fetchTodos.handler
    events:
      - http:
          path: /todos
          method: get
  fetchTodo:
    handler: src/fetchTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: get
  updateTodo:
    handler: src/updateTodo.handler
    events:
      - http:
          path: /todos/{id}
          method: put

# Resources
resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TodoTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
